Creates new rpc functions doShield and shieldBalanceToOrchard. Adds s…
zingolabs/zingo-pc pull request #67
Opened 2023-06-04 18:07 UTC by elijahhampton

**Proposed changes**
 Creates new rpc functions doShield and shieldBalanceToOrchard. Adds shieldBalanceToOrchard to <AddressBook />. Adds shieldBalanceToOrchard to <Receive />.

**General Notes**
Note: This merge request may only be seen as a draft as there are some questions that will probably need to be addressed:

1. Is this the desired placement of the Shield button? 
2. The UI freezes during the "shielding" operation.  I can tackle a general UI loader in this PR or leave the PR to this one issue.
3. I used my prettier config on these files without much thought. I can revert the prettier changes or create a new PR without the prettier changes.

**Visuals**
New Button (This button is "Shield Balance" now)

<img width="1345" alt="Captura de pantalla 2023-06-03 a la(s) 6 26 14 p m" src="https://github.com/zingolabs/zingo-pc/assets/26151387/502e6533-24c5-496c-a364-0644604e93cd">

Working Error State

<img width="1345" alt="Captura de pantalla 2023-06-03 a la(s) 6 26 33 p m" src="https://github.com/zingolabs/zingo-pc/assets/26151387/08da76df-a6b3-4fae-95ee-428884125cc1">

See list of transactions here. This involves a number of transactions I made sending ZEC to my transparent address and shielding it.

https://blockchair.com/zcash/address/t1Zs9uxRyN6Knd6kDHfRKjLjn5JchnAPFN8

2023-06-04 18:20 UTC, juanky201271 commented
Aja!!!!!.... Thanks for your contribution... I need to find time to review this PR, I'll do tomorrow hopefully. Looks good though.

2023-07-01 17:41 UTC, elijahhampton commented
Updates completed. Change "shield balance" to "shield balance to orchard".

Adds functionality to shield sapling to orchard separately from transparent.

2023-07-02 10:09 UTC, juanky201271 commented
> Updates completed. Change "shield balance" to "shield balance to orchard".
> 
> Adds functionality to shield sapling to orchard separately from transparent.
> 
> @juanky201271

Looks pretty good, I need to test it in local before merge it...

2023-07-02 18:40 UTC, juanky201271 requested changes

2023-07-02 18:40 UTC, juanky201271 commented on src/components/receive/components/AddressBlock.tsx
> +              {type === AddressType.transparent && (
I think you need to check if there is something to shield, if the transparent balance is 0 make no sense to show this button.

2023-07-02 18:40 UTC, juanky201271 commented on src/components/receive/components/AddressBlock.tsx
> +              {type === AddressType.sapling && (
I think you need to check if there is something to shield, if the sapling balance is 0 make no sense to show this button.

2023-07-02 19:03 UTC, juanky201271 requested changes

2023-07-02 19:03 UTC, juanky201271 commented on src/root/Routes.tsx
> +      throw new Error(result)
I think the user needs some feedback here, you can use `openerrormodal` here if the result have no `txid`
And the user needs some feedback even if the transaction finished successfully... using this `txid` as well.

2023-07-02 19:03 UTC, juanky201271 commented on src/root/Routes.tsx
> +      throw new Error(result)
same here.

2023-07-03 10:27 UTC, juanky201271 commented
I resolved the conflicts...

2023-07-19 09:09 UTC, juanky201271 commented
@elijahhampton How's it going? If you are really busy I can take this PR from here & finish it in your branch... I'm happy to help.
And Thanks.

cc: @Edicksonjga

2023-07-21 11:28 UTC, juanky201271 commented
@elijahhampton Well, I'm going to wait a little bit. I tried to contact with you by several channels... and no luck. Please tell me what do you think... about this PR progression...

2023-07-25 19:42 UTC, merged

2023-08-08 18:45 UTC, elijahhampton commented
> @elijahhampton Well, I'm going to wait a little bit. I tried to contact with you by several channels... and no luck. Please tell me what do you think... about this PR progression...

Thank you for finishing the PR. I responded to your message through Element.